name: Selenium Demoblaze

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main   

jobs:
  Selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/Selenium
          
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  
          
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Compile Selenium Code
        run: mvn clean

      - name: Run Selenium tests
        run: mvn test
      
      - name: Archive HTML report
        uses: actions/upload-artifact@v2
        with:
          name: Selenium-report
          path: |
                target/site/surefire-report
          retention-days: 30
