name: Selenium Demoblaze

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main   

jobs:
  Selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: feature/Selenium
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  
          
      - uses: browser-actions/setup-chrome@latest
      
      - run: chrome --version
      
      - name: Run Selenium tests
        run: mvn test
